spring.application.name=drone-backend
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/drone_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always

# JWT
jwt.secret=jfaklsddjfklsdgklsdghsdfklghsdfklhskfldhs
jwt.expiration=3600000
jwt.refresh-expiration=604800000


# TRTC
trtc.sdk-app-id=1600131769
trtc.secret-key=3e40ca1e57eb9be8b5bb964cf81841b1144c1cbc8b302db0581b2bb1319393da
trtc.room-expire=86400

amap.key=2eff2f4cf9a1d4d6fd75891a2c7e4ab4
amap.security-key=352d8eb3f6f94437cfa3035541bc6b2e